let arrows = [
	"FaAngleDoubleRight", "FaAngleDoubleUp", "FaAngleDown", "FaAngleLeft", "FaAngleRight", "FaAngleUp", "FaArrowLeft", "FaArrowDown", "FaArrowCircleUp", "FaArrowCircleRight",
	"FaArrowCircleLeft", "FaArrowCircleDown", "FaArrowAltCircleUp", "FaArrowAltCircleRight", "FaArrowAltCircleLeft", "FaArrowAltCircleDown",
	"FaCaretDown", "FaCaretLeft", "FaCaretRight", "FaCaretSquareDown", "FaCaretSquareLeft", "FaCaretSquareRight", "FaCaretSquareUp", "FaCaretUp", "FaChevronRight", "FaChevronLeft",
	"FaChevronDown", "FaChevronCircleUp", "FaChevronCircleRight", "FaChevronCircleLeft", "FaChevronCircleDown", "FaChevronUp", "FaCompress", "FaCompressAlt",
	"FaCompressArrowsAlt", "FaDownload", "FaExchangeAlt", "FaExternalLinkAlt", "FaExternalLinkSquareAlt", "FaGetPocket", "FaForward", "FaLevelDownAlt", "FaLevelUpAlt", "FaLongArrowAltUp", "FaLongArrowAltRight",
	"FaLongArrowAltLeft", "FaLongArrowAltDown", "FaMixer", "FaRedoAlt", "FaRedo", "FaRegArrowAltCircleDown", "FaRegArrowAltCircleLeft", "FaRegArrowAltCircleRight",
	"FaRegArrowAltCircleUp", "FaRegCaretSquareDown", "FaRegCaretSquareLeft", "FaRegCaretSquareRight", "FaRegCaretSquareUp", "FaReplyAll", "FaReply", "FaShare", "FaSignOutAlt", "FaSignInAlt", "FaSortAlphaDown", "FaSortAlphaDownAlt",
	"FaSortAlphaUp", "FaSortAlphaUpAlt", "FaSortAmountDown", "FaSortAmountDownAlt", "FaSortAmountUp", "FaSortAmountUpAlt", "FaSortDown", "FaSortNumericDown", "FaSortNumericDownAlt",
	"FaSortNumericUp", "FaSortNumericUpAlt", "FaSortUp", "FaStepForward", "FaStepBackward", "FaTextHeight", "FaSyncAlt", "FaSync", "FaUndo", "FaUndoAlt", "BsArrow90DegDown", "BsArrow90DegLeft", "BsArrow90DegRight",
	"BsArrow90DegUp", "BsArrowBarDown", "BsArrowBarLeft", "BsArrowBarRight", "BsArrowBarUp", "BsArrowClockwise", "BsArrowCounterclockwise", "BsArrowDown", "BsArrowDownCircle", "BsArrowDownCircleFill", "BsArrowDownLeft", "BsArrowDownLeftCircle",
	"BsArrowDownLeftCircleFill", "BsArrowDownLeftSquare", "BsArrowDownLeftSquareFill", "BsArrowDownRight", "BsArrowRightCircleFill", "BsArrowRightCircle", "BsArrowRight", "BsArrowReturnRight",
	"BsArrowReturnLeft", "BsArrowRepeat", "BsArrowLeftSquareFill", "BsArrowLeftSquare", "BsArrowLeftShort", "BsArrowLeftRight", "BsArrowLeftCircleFill", "BsArrowLeftCircle", "BsArrowLeft", "BsArrowDownUp",
	"BsArrowDownSquareFill", "BsArrowDownSquare", "BsArrowDownShort", "BsArrowDownRightSquareFill", "BsArrowDownRightSquare", "BsArrowDownRightCircleFill", "BsArrowDownRightCircle", "BsArrowRightShort",
	"BsArrowRightSquare", "BsArrowRightSquareFill", "BsArrowUp", "BsArrowUpCircle", "BsArrowThroughHeartFill", "BsArrowThroughHeart", "BsArrowUpCircle", "BsArrowUpCircleFill",
	"BsArrowUpLeft", "BsArrowUpLeftCircle", "BsArrowUpLeftSquare", "BsArrowUpLeftSquareFill", "BsArrowUpRight", "BsArrowUpRightCircle", "BsArrowUpRightCircleFill",
	"BsArrowUpRightSquare", "BsArrowUpRightSquareFill", "BsArrowUpShort", "BsArrowUpSquare", "BsArrowUpSquareFill", "BsArrowsMove", "BsBoxArrowDownLeft", "BsBoxArrowDownRight", "BsBoxArrowInDown", "BsBoxArrowInDownLeft",
	"BsBoxArrowInDownRight", "BsBoxArrowInLeft", "BsBoxArrowInRight", "BsBoxArrowInUp", "BsBoxArrowInUpLeft", "BsBoxArrowInUpRight",
	"BsBoxArrowLeft", "BsBoxArrowRight", "BsBoxArrowUp", "BsBoxArrowUpLeft", "BsBoxArrowUpRight", "BsCaretDownSquare", "BsCaretDownSquareFill",
	"BsCaretLeft", "BsCaretLeftFill", "BsCaretLeftSquare", "BsCaretLeftSquareFill", "BsCaretRight", "BsCaretRightFill", "BsCaretRightSquare", "BsCaretUp", "BsCaretUpFill", "BsCaretUpSquare", "BsCaretUpSquareFill",
	"BsChevronBarContract", "BsChevronBarDown", "BsChevronBarExpand", "BsChevronBarLeft", "BsChevronBarRight", "BsChevronBarUp",
	"BsChevronCompactDown", "BsChevronCompactLeft", "BsChevronCompactRight", "BsChevronCompactUp", "BsChevronContract", "BsChevronDoubleDown",
	"BsChevronDoubleLeft", "BsChevronDoubleRight", "BsChevronDoubleUp", "BsChevronDown", "BsChevronExpand", "BsChevronLeft", "BsChevronRight", "BsChevronUp", "BsCloudArrowUpFill",
	"BsCloudDownload", "BsCloudDownloadFill", "BsCloudUpload", "BsCloudUploadFill", "BsDownload", "BsFastForward", "BsFastForwardBtn", "BsFastForwardBtnFill", "BsFastForwardCircle", "BsFastForwardCircleFill", "BsFastForwardFill",
	"BsFileArrowDown", "BsFileArrowDownFill", "BsFileArrowUp", "BsFileArrowUpFill", "BsFillCaretDownFill", "BsFillCaretDownSquareFill", "BsFillCaretLeftFill", "BsFillCaretLeftSquareFill",
	"BsFillCaretRightFill", "BsFillCaretRightSquareFill", "BsFillCaretUpFill", "BsFillCaretUpSquareFill", "BsFillCloudArrowDownFill", "BsFillCloudArrowUpFill", "BsFillCloudDownloadFill", "BsFillCloudUploadFill",
	"BsFillReplyAllFill", "BsFillReplyFill", "BsFillRewindBtnFill", "BsFillRewindCircleFill", "BsFillRewindFill", "BsRepeat",
	"BsRepeat1", "BsReply", "BsReplyAll", "BsReplyAllFill", "BsReplyFill", "BsReverseBackspaceReverse", "BsRewindBtn", "BsRewindBtnFill", "BsSaveFill", "BsSave2Fill", "BsSave2", "BsSave",
	"BsSignMergeRight", "BsSignMergeLeftFill", "BsSignMergeLeft", "BsSignTurnSlightRightFill", "BsSignTurnSlightRight", "BsSignTurnSlightLeftFill", "BsSignTurnSlightLeft",
	"BsSignTurnRightFill", "BsSignTurnRight", "BsSignTurnLeftFill", "BsSignTurnLeft", "BsSkipEndBtnFill", "BsSkipEndBtn", "BsSkipEnd", "BsSkipBackwardFill", "BsSkipBackwardCircleFill", "BsSkipBackwardCircle",
	"BsSkipBackwardBtnFill", "BsSkipBackwardBtn", "BsSkipBackward", "BsSkipEndCircle", "BsSkipEndCircleFill", "BsSkipEndFill", "BsSkipForward", "BsSkipForwardBtn",
	"BsSkipForwardBtnFill", "BsSkipForwardCircle", "BsSkipForwardCircleFill", "BsSkipForwardFill", "BsSkipStart", "BsSkipStartBtn", "BsSkipStartBtnFill",
	"BsSkipStartCircle", "BsSkipStartCircleFill", "BsSkipStartFill", "AiFillCaretDown", "AiFillCaretLeft", "AiFillCaretRight", "AiFillCaretUp", "AiFillFastForward", "AiFillForward", "AiFillLeftCircle",
	"AiFillLeftSquare", "AiFillStepForward", "AiFillStepBackward", "AiOutlineArrowDown", "AiOutlineArrowLeft", "AiOutlineArrowRight", "AiOutlineArrowUp", "AiOutlineArrowsAlt",
	"AiOutlineBackward", "AiOutlineCaretDown", "AiOutlineCaretLeft", "AiOutlineCaretRight", "AiOutlineCaretUp", "AiOutlineColumnHeight", "AiOutlineColumnWidth",
	"AiOutlineCompress", "AiOutlineDoubleLeft", "AiOutlineDoubleRight", "AiOutlineDown", "AiOutlineDownCircle", "AiOutlineDownSquare",
	"AiOutlineDownload", "AiOutlineDrag", "AiOutlineExpand", "AiOutlineExpandAlt", "AiOutlineExport", "AiOutlineFall", "AiOutlineFastBackward", "AiOutlineFastForward", "AiOutlineFullscreen", "AiOutlineFullscreenExit",
	"AiOutlineLineHeight", "AiOutlineLeft", "AiOutlineLeftCircle", "AiOutlineLeftSquare", "AiOutlineNodeCollapse", "AiOutlineNodeIndex",
	"AiOutlineRedo", "AiOutlineReload", "AiOutlineRetweet", "AiOutlineRight", "AiOutlineRightCircle", "AiOutlineRightSquare", "AiOutlineRise", "AiOutlineRollback", "AiOutlineRotateLeft", "AiOutlineRotateRight",
	"AiOutlineSwapRight", "AiOutlineSwapLeft", "AiOutlineSwap", "AiOutlineStock", "AiOutlineSortDescending", "AiOutlineSortAscending", "AiOutlineToTop", "AiOutlineUndo",
	"AiOutlineUp", "AiOutlineUpCircle", "AiOutlineUpSquare", "AiOutlineUpload", "AiOutlineVerticalRight", "AiOutlineVerticalLeft",
	"AiOutlineVerticalAlignTop", "AiOutlineVerticalAlignMiddle", "AiOutlineVerticalAlignBottom"
];

export default arrows;