let mediaIcons = ["FaMicrochip", "FaMicrophone", "FaMicrophoneAlt", "FaMicrophoneAltSlash", "FaMicrophoneSlash", "FaBlenderPhone", "FaCamera", "FaCameraRetro", "FaPhotoVideo", "BsFillBoomboxFill"
, "BsFillCameraFill", "BsFillCameraReelsFill", "BsFillCameraVideoFill", "BsFillCameraVideoOffFill", "FaSort", "FaPlay", "FaPlayCircle", "FaForward", "FaBackward", "FaFastBackward", "FaFastForward",
"BsFastForward", "BsFastForwardBtn", "BsFastForwardBtnFill", "BsFastForwardCircle", "BsFastForwardCircleFill", "BsFastForwardFill", "FaStop", "FaStopCircle",
"FaRegStopCircle", "FaRegCheckCircle", "FaRegCheckSquare", "FaStepForward", "FaStepBackward", "FaSync", "FaSyncAlt", "FaVolumeMute", "FaVolumeOff", "FaVolumeUp", "FaRedo", "FaRedoAlt", "FaRecycle", "FaQuestion", "FaQuestionCircle", "FaQuoteLeft",
"FaQuoteRight", "FaTag", "FaTags", "FaWindowMaximize", "FaFilm", "FaAudioDescription", "FaBluetooth", "FaBluetoothB", "FaDownload", "FaBolt",
"FaClosedCaptioning", "FaCompactDisc", "FaDigitalTachoGraph", "FaEject", "FaPowerOff", "FaDesktop", "FaTty", "FaPhoneAlt", "FaPhoneSlash", "FaPhoneSquare", "FaPhoneSquareAlt", "BsFillTelephoneForwardFill", "BsFillTelephoneInboundFill",
"BsFillTelephoneMinusFill", "BsFillTelephoneOutboundFill", "BsFillTelephonePlusFill", "BsFillTelephoneXFill", "BsFillUnlockFill",
"BsFillUsbDriveFill", "BsFillUsbPlugFill", "BsFillUsbMiniFill", "BsFillUsbMicroFill",
"BsFillUsbFill", "BsFillVolumeDownFill", "BsFillVolumeMuteFill", "BsFillVolumeOffFill", "BsFillVolumeUpFill", "BsVolumeUp", "BsVolumeOff", "BsVolumeMute",
"BsVolumeDown", "BsGeoAlt", "BsGeoAltFill", "BsLightning", "BsLightningCharge", "BsLightningChargeFill", "BsLightningFill", "BsLink",
"BsLink45Deg", "BsMegaphone", "BsMegaphoneFill", "BsMicFill", "BsMicMute", "BsMicMuteFill", "BsMic", "FaHeadset", "FaHeadphones", "FaHeadphonesAlt", "FaItunes", "FaItunesNote", "FaHourglass",
"FaHourglassEnd", "FaHourglassHalf", "FaHourglassStart", "FaSdCard", "FaScroll", "FaSave", "FaRss", "FaRssSquare", "FaRegWindowRestore", "FaRegWindowMaximize",
"FaRegPauseCircle", "FaRegPlayCircle", "FaRegPlusSquare", "FaPhoneVolume", "BsPlayCircleFill", "BsPlayFill", "BsRecycle", "BsRepeat", "BsRepeat1", "BsRewindCircle",
"BsRewindCircleFill", "BsRewindFill", "BsRewindBtnFill", "BsRewindBtn", "BsRewind", "BsShuffle", "FaPlusCircle", "FaPlusSquare", "FaPlus", "FaRegSquare",
"FaBullhorn", "FaBrush", "FaSlidersH", "FaSignal", "FaSitemap", "FaTasks", "BsBullseye", "FaTabletAlt", "FaTablet",
"FaRetweet", "FaShare", "FaShareSquare", "FaShareAltSquare", "FaReply", "FaReplyAll", "FaRegShareSquare", "FaRegSave", "FaRegObjectGroup",
"FaRegObjectUngroup", "FaRegMoon", "FaRandom", "FaMinusCircle", "FaMinusSquare", "FaMinus", "FaLink", "FaLock", "FaLockOpen", "BsBadge4KFill", "BsBadge8K",
"BsBadge8KFill", "BsBadgeAd", "BsBadgeAdFill", "BsBadgeAr", "BsBadgeArFill", "BsBadgeCc", "BsBadgeCcFill", "BsBadgeHd", "BsBadgeHdFill", "BsBadgeSd",
"BsBadgeSdFill", "BsBadgeTm", "BsBadgeTmFill", "BsBadgeVo", "BsBadgeVoFill", "BsBadgeVr", "BsBadgeVrFill", "BsBadgeWc", "BsBadgeWcFill", "BsCast", "BsCassetteFill", "BsCassette", "BsCcCircle", "BsCcCircleFill", "BsCcSquare", "BsCcSquareFill", "BsDisplay", "BsDisplayFill", "BsMusicNote",
"BsMusicNoteBeamed", "BsMusicNoteList", "BsPaperclip", "BsPauseBtn", "BsPause", "BsPauseBtnFill", "BsPauseCircle", "BsPauseCircleFill", "BsPauseFill", "BsPlayFill", "BsPhoneVibrate",
"BsPhoneVibrateFill", "BsPhoneLandscapeFill", "BsSkipBackward", "BsSkipBackwardBtn", "BsSkipBackwardBtnFill", "BsSkipBackwardCircle", "BsSkipBackwardCircleFill",
"BsSkipBackwardFill", "BsSkipEnd", "BsSkipEndBtn", "BsSkipEndBtnFill", "BsSkipStartFill", "BsSkipStartCircleFill", "BsSkipStartCircle", "BsSkipStartBtnFill",
"BsSkipStartBtn", "BsSkipStart", "BsSkipForwardFill", "BsSkipForwardCircleFill", "BsSkipForwardCircle", "BsSkipForwardBtnFill", "BsSkipForwardBtn", "BsSkipForward", "BsSkipEndFill",
"BsSkipEndCircleFill", "BsStop", "BsStopBtn", "BsStopBtnFill", "BsStopCircle", "BsStopCircleFill", "BsStopFill", "BsWifi", "BsWifi1", "BsWifi2", "BsWifiOff", "BsZoomOut", "BsZoomIn", "BsUsbPlugFill", "BsUpc", "BsUpcScan", "BsTrash3Fill",
"BsTrashFill", "BsTrash", "BsThunderbolt", "BsThunderboltFill", "BsShare", "BsShareFill",
"AiFillCamera", "AiFillBulb", "AiFillAudio", "AiFillBackward", "AiFillCustomerService", "AiFillLock", "AiFillStepBackward",
"AiFillStepForward", "AiFillUsb", "AiFillVideoCamera", "AiFillWarning", "AiOutlineBackward", "AiOutlineFastBackward", "AiOutlineFastForward", "AiOutlineForward", "AiOutlineLogin",
"AiOutlineLogout", "AiOutlinePause", "AiOutlinePauseCircle", "AiOutlinePlayCircle", "AiOutlinePlaySquare", "AiOutlinePlus", "AiOutlinePlusCircle",
"AiOutlinePlusSquare", "AiOutlinePushpin", "AiOutlinePoweroff", "AiOutlineQuestion", "AiOutlineQuestionCircle",
"AiOutlineRetweet", "AiOutlineRedo", "AiOutlineReload", "AiOutlineTags", "AiOutlineTag", "AiOutlineSync", "AiOutlineUndo", "AiOutlineThunderbolt",
"AiOutlineWifi", "AiOutlineYoutube", "AiOutlineZoomIn", "AiOutlineZoomOut", "AiTwotoneAudio", "AiTwotoneBell", "AiTwotoneCode", "AiTwotoneNotification",
"AiTwotoneTags", "AiTwotoneSave", "AiTwotoneThunderbolt", "AiTwotoneSound"
];

export default mediaIcons;