let messaging = [
	"FaSistrix", "FaSearch", "FaSearchDollar", "FaSearchLocation", "FaSearchMinus", "FaSearchPlus",
"FaSearchengin", "AiOutlineComment","AiOutlineEnvironment","AiOutlineMail","AiOutlineNotification","AiOutlineMinus", "BsSendCheck", "BsSendCheckFill", "BsSendDash", "BsSendDashFill", "BsSendExclamation", "BsSendExclamationFill",
"BsSendFill", "BsSendPlus", "BsSendPlusFill", "BsSendSlash", "BsSendSlashFill", "BsSendX", "BsSendXFillBsShare", "BsShareFill", "BsSendCheck", "BsSend", "BsChat", "BsChatDots",
"BsChatDotsFill", "BsChatFill", "BsChatHeart", "BsChatHeartFill", "BsChatLeft", "BsChatLeftDots", "BsChatLeftDotsFill", "BsChatLeftFill", "BsChatLeftHeart", "BsChatLeftHeartFill",
"BsChatLeftQuote", "BsChatLeftQuoteFill", "BsChatLeftText", "BsChatLeftTextFill", "BsChatQuote", "BsChatQuoteFill", "BsChatRight", "BsChatRightDots",
"BsChatRightDotsFill", "BsChatRightFill", "BsChatRightHeart", "BsChatRightHeartFill", "BsChatRightQuote", "BsChatRightQuoteFill", "BsCheck", "BsChatText", "BsChatSquareTextFill", "BsChatSquareText",
"BsChatSquareQuoteFill", "BsChatSquareQuote", "BsChatSquareHeartFill", "BsChatSquareHeart", "BsChatSquareFill", "BsChatSquareDotsFill",
"BsChatSquareDots", "BsChatSquare", "BsChatRightTextFill", "BsChatRightText", "FaShare", "FaShareSquare", "FaShareAltSquare", "FaRegShareSquare", "BsShare", "BsShareFill", "BsSendXFillBsShare", "BsShareFill", "FaReply", "FaReplyAll", "BsReply", "BsReplyAll", "BsReplyAllFill", "BsReplyFill",
"BsBookmarkCheck", "BsBookmarkCheckFill",
"BsBookmarkDash", "BsBookmarkDashFill", "BsBookmarkFill", "BsBookmarkHeart", "BsBookmarkHeartFill", "BsBookmarkPlus", "BsBookmarkPlusFill", "BsBookmarkStar",
"BsBookmarkStarFill", "BsBookmarkX", "BsBookmarkXFill", "BsBookmarks", "BsBookmarksFill", "BsTrash3Fill",
"BsTrashFill", "BsTrash", "BsBell", "BsBellFill", "BsBellSlash", "BsBellSlashFill", "BsBag", "BsBagCheck", "BsBagCheckFill", "BsBagFill", "BsBagHeart", "BsBagHeartFill", "BsBagPlus",
"BsBagPlusFill", "BsBagX", "BsBagXFill", "BsBasket", "BsBasket2", "BsBasket2Fill", "BsBasket3", "BsBasket3Fill", "BsBasketFill", "BsBluetooth", "BsBoxArrowDown", "BsBoxArrowDownLeft",
"BsBoxArrowDownRight", "BsBoxArrowInDown", "BsBoxArrowInDownLeft", "BsBoxArrowInDownRight", "BsBoxArrowInLeft", "BsBoxArrowInRight", "BsBoxArrowInUp", "BsBoxArrowInUpLeft",
"BsBoxArrowInUpRight", "BsBoxArrowLeft", "BsBoxArrowRight", "BsBoxArrowUpLeft", "BsBoxArrowUpRight", "BsBroadcastPin", "BsCart", "BsCart2", "BsCart3", "BsCart4", "BsCartCheck", "BsCartCheckFill", "BsCartDash",
"BsCartDashFill", "BsCartFill", "BsCartPlus", "BsCartPlusFill", "BsCartX", "BsCartXFill", "BsClipboardX", "BsClipboardPulse", "BsClipboardPlusFill", "BsClipboardPlus", "BsClipboardMinusFill", "BsClipboardMinus",
"BsClipboardHeartFill", "BsClipboardHeart", "BsClipboardFill", "BsClipboardDataFill", "BsClipboardData", "BsClipboardCheckFill", "BsClipboardCheck",
"BsClipboard2XFill", "BsClipboard2X", "BsClipboard2PulseFill", "BsCloud", "BsCloudHazeFill", "BsCloudHaze2Fill", "BsCloudHaze2", "BsCloudHaze", "BsCloudHailFill", "BsCloudHail", "BsCloudFogFill", "BsCloudFog2Fill", "BsCloudFog2", "BsCloudFog", "BsCloudFill", "BsCloudDrizzleFill", "BsCloudDrizzle",
"BsCloudDownloadFill", "BsCloudDownload", "BsCloudCheckFill", "BsCloudCheck", "BsCloudArrowUpFill", "BsCloudCheckFill", "BsCloudArrowUpFill", "BsCloudArrowUp", "BsCloudArrowDownFill", "BsCloudArrowDown", "BsCloudLightning", "BsCloudLightningFill",
"BsCloudLightningRain", "BsCloudLightningRainFill", "BsCloudMinus", "BsCloudMinusFill", "BsCloudMoon", "BsCloudMoonFill", "BsCloudPlus", "BsCloudPlusFill", "BsCloudRain", "BsCloudRainFill", "BsCloudRainHeavy",
"BsCloudRainHeavyFill", "BsCloudSlash", "BsCloudSlashFill", "BsCloudSleet", "BsCloudSleetFill", "BsCloudSnow", "BsCloudSnowFill", "BsCloudSun", "BsCloudSunFill", "BsCloudUpload", "BsCloudUploadFill", "BsClouds", "BsCloudsFill", "BsCloudy",
"BsCloudyFill", "BsDownload", "BsEnvelope", "BsEnvelopeAt", "BsEnvelopeAtFill", "BsEnvelopeCheck", "BsEnvelopeCheckFill", "BsEnvelopeDash", "BsEnvelopeDashFill", "BsEnvelopeExclamation", "BsEnvelopeExclamationFill",
"BsEnvelopeFill", "BsEnvelopeHeart", "BsEnvelopeHeartFill", "BsEnvelopeOpen", "BsEnvelopeOpenFill", "BsEnvelopeOpenHeart", "BsEnvelopeOpenHeartFill", "BsEnvelopePaper", "BsEnvelopePaperFill",
"BsEnvelopePaperHeart", "BsEnvelopePaperHeartFill", "BsEnvelopePlus", "BsEnvelopePlusFill", "BsEnvelopeSlash", "BsEnvelopeSlashFill", "BsEnvelopeX", "BsEnvelopeXFill", "BsEvFrontFill", "BsEvFront", "BsEscape", "BsExclamation", "BsExclamationCircle", "BsExclamationCircleFill",
"BsExclamationDiamond", "BsExclamationDiamondFill", "BsExclamationLg", "BsExclamationOctagon", "BsExclamationSquare", "BsExclamationSquareFill", "BsFillFilterSquareFill", "BsFillFilterCircleFill",
"BsFillTelephoneFill", "BsFillTelephoneForwardFill", "BsFillTelephoneInboundFill", "BsFillTelephoneMinusFill", "BsFillTelephoneOutboundFill", "BsFillTelephonePlusFill",
"BsFillTelephoneXFill", "BsGlobe", "BsGlobe2", "BsGlobeAmericas", "BsGlobeAsiaAustralia", "BsGlobeCentralSouthAsia", "BsLine", "BsLink", "BsLink45Deg", "BsPaperclip", "BsPatchCheck", "BsPatchCheckFill", "BsPatchExclamation",
"BsPatchExclamationFill", "BsPatchMinus", "BsPatchMinusFill", "BsPatchPlus", "BsPatchQuestion", "BsPatchQuestionFill", "BsGlobeEuropeAfrica",
"BsExclamationTriangle", "BsExclamationTriangleFill", "BsQuestion", "BsQuestionCircle", "BsQuestionCircleFill", "BsQuestionDiamond", "BsQuestionDiamondFill", "BsQuestionLg", "BsQuestionOctagon", "BsQuestionOctagonFill",
"BsQuestionSquare", "BsQuestionSquareFill", "BsTag", "BsTagFill", "BsTags", "BsTagsFill", "BsTelegram", "BsWhatsapp", "FaBluetoothB", "FaBluetooth", "FaBullhorn", "FaCheck",
"FaCheckCircle", "FaCheckSquare", "FaCheese", "FaCloudDownloadAlt", "FaCloudRain", "FaComment", "FaCommentAlt", "FaCommentDollar", "FaCommentDots", "FaCommentMedical", "FaCommentSlash", "FaComments",
"FaCommentsDollar", "FaEdit", "FaEnvelope", "FaEnvelopeOpen", "FaEnvelopeOpenText", "FaEnvelopeSquare", "FaExternalLinkAlt", "FaExternalLinkSquareAlt", "FaExchangeAlt", "FaExclamation", "FaExclamationCircle",
"FaExclamationTriangle", "FaExpandAlt", "FaInfo", "FaInfoCircle", "FaLocationArrow", "FaMapMarkerAlt", "FaMapMarker", "FaMapPin", "FaPaperclip", "FaPaperPlane", "FaPhone", "FaPhoneAlt", "FaPhoneSlash", "FaPhoneSquare",
"FaPhoneSquareAlt", "FaPhoneVolume", "FaPlus", "FaPlusCircle", "FaPlusSquare", "FaRecycle", "FaRegBell", "FaRegCheckCircle", "FaRegCheckSquare", "FaRegEnvelopeOpen", "FaRegEnvelope", "FaRegStar", "FaShareAlt", "FaSync", "FaSyncAlt", "FaUndoAlt", "FaUndo", "FaSms"
];

export default messaging;